site_name: PythonCode Docs
site_description: Автоматическая документация проекта PythonCode
site_author: voronovich
repo_url: https://github.com/<ТВОЙ_НИК>/<ТВОЙ_РЕПОЗИТОРИЙ>
repo_name: GitHub

theme:
  name: material
  language: ru
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.top
    - content.code.copy
    - content.action.edit
    - content.action.view
  palette:
    - scheme: default
      primary: indigo
      accent: pink
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Тёмная тема
      primary: indigo
      accent: pink

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_source: true


nav:
  - Главная: index.md
  - Руководство:
      - Конфигурация: config_manager.md
      - Валидаторы: validators.md
      - База данных: database.md
  - Модели:
      - Категории: categories_model.md
      - Элементы: items_model.md
      - Поставщики: suppliers_model.md
      - Спецификации: specification_models.md
      - Таблицы спецификаций: specification_items_table_model.md
      - Прокси фильтр: filter_proxy_model.md
  - Адаптеры:
      - Supplier List Adapter: supplier_list_adapter.md
  - API:
      - Обзор: api/index.md
  - Генерация документации: generate_docs.md
