name: Deploy MkDocs documentation

on:
  push:
    branches:
      - main  # или master, если у тебя так называется ветка
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Upgrade pip and install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material mkdocstrings[python] mkdocs-autorefs

      - name: Verify MkDocs installation
        run: mkdocs --version

      - name: Build and deploy documentation
        run: mkdocs gh-deploy --force

